version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
