use utoipa::OpenApi;

/// The `__path_*` modules are generated by `#[utoipa::path]` on each handler.
use crate::router::get::get_list::__path_get_albums;
use crate::router::post::authenticate::__path_authenticate;
use crate::router::put::assign_album::__path_assign_album;

#[derive(OpenApi)]
#[openapi(
    paths(authenticate, get_albums, assign_album),
    components(schemas(
        crate::router::get::get_list::AlbumInfo,
        crate::router::put::assign_album::AssignAlbumData,
    ))
)]
pub struct ApiDoc;

/// Serialize the `OpenAPI` spec as `JSON`.
///
/// # Panics
/// Panics if the `OpenAPI` serializer encounters a type it cannot handle (should
/// not happen with the current schema set — all types derive `Serialize`).
#[must_use]
pub fn generate_json() -> String {
    ApiDoc::openapi()
        .to_json()
        .expect("OpenAPI serialization failed")
}
