use std::fmt::Write;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let backend_root = Path::new(&manifest_dir);

    generate_scenarios_rs(backend_root);
}

fn generate_scenarios_rs(backend_root: &Path) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let test_dir = backend_root.join("tests").join("scenarios");
    let selftest_dir = test_dir.join("selftest");

    println!("cargo:rerun-if-changed={}", test_dir.display());

    let mut out = String::new();
    macro_rules! wln {
        ($($arg:tt)*) => {
            let _ = writeln!(out, $($arg)*);
        };
    }

    wln!("// Auto-generated by build.rs. Do not edit manually.");
    wln!();

    // Generate test for each YAML scenario
    let mut entries: Vec<_> = std::fs::read_dir(&test_dir)
        .unwrap_or_else(|e| panic!("read scenarios dir {}: {e}", test_dir.display()))
        .filter_map(std::result::Result::ok)
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "yaml"))
        .collect();
    entries.sort_by_key(std::fs::DirEntry::file_name);

    for entry in &entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let test_name = format!("scenario_{stem}");
        wln!("#[test]");
        wln!("fn {test_name}() {{");
        wln!("    run_backend_scenario(\"{stem}\");");
        wln!("}}");
        wln!();
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // Generate test for each selftest YAML
    if selftest_dir.exists() {
        println!("cargo:rerun-if-changed={}", selftest_dir.display());
        let mut selftest_entries: Vec<_> = std::fs::read_dir(&selftest_dir)
            .unwrap_or_else(|e| panic!("read selftest dir {}: {e}", selftest_dir.display()))
            .filter_map(std::result::Result::ok)
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "yaml"))
            .collect();
        selftest_entries.sort_by_key(std::fs::DirEntry::file_name);

        for entry in &selftest_entries {
            let path = entry.path();
            let stem = path.file_stem().unwrap().to_str().unwrap();
            let test_name = format!("selftest_{stem}");
            wln!("#[test]");
            wln!("fn {test_name}() {{");
            wln!("    run_selftest_scenario(\"{stem}\");");
            wln!("}}");
            wln!();
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let dest = Path::new(&out_dir).join("scenarios.rs");
    std::fs::write(&dest, out.as_bytes())
        .unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
