use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::{Path, PathBuf};

use openapi_sanity::Finding;

/// A handler registered by a `routes![...]` block, with the group it was found in.
#[derive(Clone)]
struct Route {
    group_prefix: String,
    module_path: String,
    handler: String,
}

/// Router files whose `routes![...]` blocks are scanned, as
/// `(group prefix, path relative to src/router)`.
///
/// A module missing from this list has its routes mounted but undocumented, which
/// the parity test in `src/tests/openapi_contract.rs` reports.
const SCANNED_MODULES: &[(&str, &str)] = &[
    ("get", "get/mod.rs"),
    ("post", "post/mod.rs"),
    ("put", "put/mod.rs"),
    ("delete", "delete.rs"),
    ("fairing", "fairing/mod.rs"),
    // `auth.rs` mounts the token renewal routes through
    // `generate_fairing_routes()`. It has to be scanned here as well,
    // otherwise its annotated handlers never reach `paths(...)` and the
    // routes are mounted but undocumented.
    ("auth", "auth.rs"),
];

#[allow(clippy::cast_precision_loss)]
fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let backend_root = Path::new(&manifest_dir);
    let router_root = backend_root.join("src").join("router");

    println!("cargo:rerun-if-changed=src/router");
    println!("cargo:rerun-if-changed=src/lib.rs");

    let all_routes = collect_all_routes(backend_root, &router_root);
    let total = all_routes.len();
    let mut annotations = AnnotationIndex::new(backend_root, &router_root);
    let mut annotated: Vec<Route> = Vec::new();
    let mut missing: Vec<Route> = Vec::new();

    for r in all_routes {
        if annotations.is_annotated(&r) {
            annotated.push(r);
        } else {
            missing.push(r);
        }
    }

    for r in &missing {
        println!(
            "cargo:warning=missing #[utoipa::path] annotation on {}::{}",
            r.module_path, r.handler
        );
    }

    let annotated_count = annotated.len();
    if total > 0 && annotated_count != total {
        let coverage_pct = (annotated_count as f64 / total as f64) * 100.0;
        println!(
            "cargo:warning=utoipa annotation coverage: {coverage_pct:.1}% ({annotated_count}/{total})"
        );
    }

    generate_openapi_rs(&annotated, &backend_root.join("src").join("openapi.rs"));
    generate_scenarios_rs(&annotated, backend_root);
}

/// Response components declared in `src/openapi_components.rs` and referenced
/// from `#[utoipa::path]` annotations. Registered in the generated `ApiDoc`.
const RESPONSE_COMPONENTS: &[&str] = &["Unauthorized"];

fn generate_openapi_rs(annotated: &[Route], dest: &Path) {
    let group_order: [&str; 6] = ["get", "post", "put", "delete", "fairing", "auth"];
    let mut annotated = annotated.to_vec();
    annotated.sort_by(|a, b| {
        let a_grp = group_order
            .iter()
            .position(|&g| g == a.group_prefix)
            .unwrap_or(99);
        let b_grp = group_order
            .iter()
            .position(|&g| g == b.group_prefix)
            .unwrap_or(99);
        a_grp
            .cmp(&b_grp)
            .then_with(|| a.module_path.cmp(&b.module_path))
            .then_with(|| a.handler.cmp(&b.handler))
    });

    let mut out = String::new();
    macro_rules! wln {
        ($($arg:tt)*) => {
            let _ = writeln!(out, $($arg)*);
        };
    }

    wln!("// Auto-generated by build.rs. Do not edit manually.");
    wln!("use utoipa::OpenApi;");
    wln!();

    // Shared response components referenced by the `#[utoipa::path]`
    // annotations below (e.g. `(status = 401, response = Unauthorized)`). One
    // list drives the import and the `components(responses(...))` registration,
    // so adding a component cannot leave the generated file with an import that
    // is registered under a different name.
    for component in RESPONSE_COMPONENTS {
        wln!("use crate::openapi_components::{component};");
    }

    for r in &annotated {
        let import_mod = if r.module_path == r.group_prefix {
            format!("crate::router::{g}", g = r.group_prefix)
        } else {
            format!(
                "crate::router::{g}::{m}",
                g = r.group_prefix,
                m = r.module_path
            )
        };
        wln!(
            "use {import_mod}::__path_{handler};",
            import_mod = import_mod,
            handler = r.handler
        );
    }

    wln!();
    wln!("#[derive(OpenApi)]");
    wln!("#[openapi(");
    wln!("    paths(");

    let mut current_group = String::new();
    for r in &annotated {
        let section = match r.group_prefix.as_str() {
            "get" => "// ── GET routes",
            "post" => "// ── POST routes",
            "put" => "// ── PUT routes",
            "delete" => "// ── DELETE routes",
            "fairing" => "// ── FAIRING routes",
            "auth" => "// ── auth routes (router/auth.rs)",
            _ => "",
        };
        if section != current_group {
            if !current_group.is_empty() {
                wln!();
            }
            wln!("        {section}");
            current_group = section.to_string();
        }
        wln!("        {},", r.handler);
    }

    wln!("    ),");
    wln!("    components(");
    wln!("        responses({})", RESPONSE_COMPONENTS.join(", "));
    wln!("    ),");
    wln!(")]");
    wln!("pub struct ApiDoc;");
    wln!();
    wln!("/// # Panics");
    wln!("/// Panics if `ApiDoc::openapi().to_json()` fails.");
    wln!("#[must_use]");
    wln!("pub fn generate_json() -> String {{");
    wln!("    ApiDoc::openapi()");
    wln!("        .to_json()");
    wln!("        .expect(\"OpenAPI serialization failed\")");
    wln!("}}");

    std::fs::write(dest, out.as_bytes()).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", dest.display());
    });
    // Do NOT rerun on dest — it's generated, would cause rebuild loop.
}

/// Which handler functions carry their own `#[utoipa::path]` annotation.
///
/// The answer is per function, not per file: a file that annotates one handler
/// says nothing about its neighbours, and crediting a sibling's annotation is how
/// a route reaches `paths(...)` carrying another operation's metadata. Each source
/// file is read and parsed once, so a module with twenty handlers is not read
/// twenty times.
struct AnnotationIndex {
    backend_root: PathBuf,
    router_root: PathBuf,
    cache: HashMap<PathBuf, HashSet<String>>,
}

impl AnnotationIndex {
    fn new(backend_root: &Path, router_root: &Path) -> Self {
        Self {
            backend_root: backend_root.to_path_buf(),
            router_root: router_root.to_path_buf(),
            cache: HashMap::new(),
        }
    }

    /// The file a route's handler function is defined in.
    fn source(&self, route: &Route) -> PathBuf {
        if route.module_path == route.group_prefix {
            self.router_root.join(format!("{}.rs", route.group_prefix))
        } else {
            self.router_root
                .join(&route.group_prefix)
                .join(format!("{}.rs", route.module_path))
        }
    }

    fn is_annotated(&mut self, route: &Route) -> bool {
        let source = self.source(route);
        if !self.cache.contains_key(&source) {
            let annotated = annotated_handlers(&self.backend_root, &source);
            self.cache.insert(source.clone(), annotated);
        }
        self.cache
            .get(&source)
            .is_some_and(|handlers| handlers.contains(&route.handler))
    }
}

/// The functions in one source file that carry a `#[utoipa::path]` annotation.
///
/// A file that cannot be read contributes no annotations, so its handlers are
/// reported as missing one rather than quietly dropped from the scan. A file that
/// does not parse is reported by the analyzer, which then contributes no
/// annotations for the same reason.
fn annotated_handlers(backend_root: &Path, source: &Path) -> HashSet<String> {
    let label = label_for(backend_root, source);
    let Ok(content) = std::fs::read_to_string(source) else {
        return HashSet::new();
    };

    let scan = openapi_sanity::scan_handlers(&label, &content);
    report(&scan.findings);
    scan.handlers
        .into_iter()
        .filter(|handler| handler.annotated)
        .map(|handler| handler.name)
        .collect()
}

/// The handlers registered by every `routes![...]` block in a scanned module.
///
/// Route order is the order the blocks appear in, which is what
/// `generate_openapi_rs` sorts on; a block that fails to parse is reported and
/// contributes no routes rather than partially registering one.
fn collect_all_routes(backend_root: &Path, router_root: &Path) -> Vec<Route> {
    let mut routes = Vec::new();

    for (group_prefix, rel_path) in SCANNED_MODULES {
        let path = router_root.join(rel_path);
        let Ok(content) = std::fs::read_to_string(&path) else {
            continue;
        };

        let label = label_for(backend_root, &path);
        let scan = openapi_sanity::scan_routes(&label, &content, group_prefix);
        report(&scan.findings);

        routes.extend(scan.handlers.into_iter().map(|handler| Route {
            group_prefix: (*group_prefix).to_string(),
            module_path: handler.module_path,
            handler: handler.handler,
        }));
    }

    routes
}

/// Surface an analyzer finding as a build warning. The crate neither prints nor
/// fails, so this is where its diagnostics reach the build log.
fn report(findings: &[Finding]) {
    for finding in findings {
        println!("cargo:warning={finding}");
    }
}

/// A file label for diagnostics, relative to the backend root when possible.
fn label_for(backend_root: &Path, source: &Path) -> String {
    source
        .strip_prefix(backend_root)
        .unwrap_or(source)
        .display()
        .to_string()
}

fn generate_scenarios_rs(_annotated: &[Route], backend_root: &Path) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let test_dir = backend_root.join("tests").join("scenarios");
    let selftest_dir = test_dir.join("selftest");

    println!("cargo:rerun-if-changed={}", test_dir.display());

    let mut out = String::new();
    macro_rules! wln {
        ($($arg:tt)*) => {
            let _ = writeln!(out, $($arg)*);
        };
    }

    wln!("// Auto-generated by build.rs. Do not edit manually.");
    wln!();

    // Generate test for each YAML scenario
    let mut entries: Vec<_> = std::fs::read_dir(&test_dir)
        .unwrap_or_else(|e| panic!("read scenarios dir {}: {e}", test_dir.display()))
        .filter_map(std::result::Result::ok)
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "yaml"))
        .collect();
    entries.sort_by_key(std::fs::DirEntry::file_name);

    for entry in &entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let test_name = format!("scenario_{stem}");
        wln!("#[test]");
        wln!("fn {test_name}() {{");
        wln!("    run_backend_scenario(\"{stem}\");");
        wln!("}}");
        wln!();
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // Generate test for each selftest YAML
    if selftest_dir.exists() {
        println!("cargo:rerun-if-changed={}", selftest_dir.display());
        let mut selftest_entries: Vec<_> = std::fs::read_dir(&selftest_dir)
            .unwrap_or_else(|e| panic!("read selftest dir {}: {e}", selftest_dir.display()))
            .filter_map(std::result::Result::ok)
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "yaml"))
            .collect();
        selftest_entries.sort_by_key(std::fs::DirEntry::file_name);

        for entry in &selftest_entries {
            let path = entry.path();
            let stem = path.file_stem().unwrap().to_str().unwrap();
            let test_name = format!("selftest_{stem}");
            wln!("#[test]");
            wln!("fn {test_name}() {{");
            wln!("    run_selftest_scenario(\"{stem}\");");
            wln!("}}");
            wln!();
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let dest = Path::new(&out_dir).join("scenarios.rs");
    std::fs::write(&dest, out.as_bytes())
        .unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
